# Generated by Django 2.0.2 on 2018-02-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.CharField(max_length=10)),
                ('points', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('contest',),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('userName',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.ManyToManyField(to='makeDB.Score'),
        ),
    ]
